version: '3'
services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - jira
#      - bitbucket
#      - confluence
#      - bamboo
#      - nexus
    env_file:
      - common.env
    networks:
      dev:
        aliases:
          - nginx
    container_name: nginx

  jira:
    image: hub.slyak.com/jira
    restart: always
    privileged: true
    volumes:
      - /opt/data/atlassian/jira:/var/atlassian/jira
    ports:
      - 8080:8080
    env_file:
      - common.env
    networks:
      dev:
        aliases:
          - jira
    container_name: jira

networks:
  dev: