version: '2.0'
services:
  jira:
    image: hub.slyak.com/jira
    restart: always
    volumes:
      - /opt/data/atlassian/jira:/var/atlassian/jira
    env_file:
      - common.env
    networks:
      dev:
        aliases:
          - jira

  bitbucket:
    image: hub.slyak.com/bitbucket
    restart: always
    links:
      - crowd
    volumes:
      - /opt/data/atlassian/bitbucket:/var/atlassian/bitbucket
      - /opt/data/atlassian/bitbucket/logs:/opt/atlassian/bitbucket/logs
    env_file:
      - common.env
    networks:
      dev:
        aliases:
          - bitbucket

  confluence:
    image: hub.slyak.com/confluence
    restart: always
    links:
      - crowd
    volumes:
      - /opt/data/atlassian/confluence:/var/atlassian/confluence
      - /opt/data/atlassian/confluence/logs:/opt/atlassian/confluence/logs
    env_file:
      - common.env
    networks:
      dev:
        aliases:
        - confluence

  crowd:
      image: hub.slyak.com/crowd
      restart: always
      volumes:
        - /opt/data/atlassian/crowd:/var/atlassian/crowd
      env_file:
        - common.env
      networks:
        dev:
          aliases:
          - crowd

networks:
  dev: