CREATE DATABASE jira CHARACTER SET utf8 COLLATE utf8_bin;
CREATE DATABASE confluence CHARACTER SET utf8 COLLATE utf8_bin;
CREATE DATABASE bitbucket CHARACTER SET utf8 COLLATE utf8_bin;
CREATE DATABASE bamboo CHARACTER SET utf8 COLLATE utf8_bin;