FROM cptactionhank/atlassian-jira:latest

ENV X_PROXY_NAME   dev.slyak.com
ENV X_PROXY_PORT   80
ENV X_PATH         /jira

#use mysql
#COPY mysql-connector-java-5.1.39.jar ${JIRA_WEB_LIB}/

#jira crack
#COPY atlassian-extras-3.2.jar ${JIRA_WEB_LIB}/

#RUN  rm "${JIRA_WEB}/atlassian-bundled-plugins/atlassian-universal-plugin-manager-plugin-2.22.9.jar"
#COPY atlassian-universal-plugin-manager-plugin-2.22.jar ${JIRA_WEB}/atlassian-bundled-plugins/